# Generated by Django 3.2.4 on 2021-06-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_photo_has_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='has_face',
            field=models.BooleanField(default=False),
        ),
    ]
